---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobsapp
  template:
    metadata:
      labels:
        app: jobsapp
      generateName: jobsapp-
    spec:
      containers:
      - name: jobsapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        envFrom:
        - configMapRef:
            name: jobsapp-config
      initContainers:
      - name: wait-for-mongodb
        image: busybox
        command: ['sh', '-c', 'until nc -z mongodb 27017; do echo waiting for mongodb; sleep 2; done;']
