replicaCount: 1

image:
  repository: oluty/eventapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000

config:
  mongoUri: "mongodb://mongodb:27017/eventdb"
  port: "5000"
  jwtSecret: "random"

initContainer:
  image: busybox

mongodb:
  name: mongodb
  replicaCount: 1
  image:
    repository: mongo
    tag: "8.0"
  service:
    name: mongodb
    port: 27017
  storage:
    size: 1Gi