replicaCount: 1

image:
  repository: oluty/jobsapp
  tag: latest

config:
  mongoUri: "mongodb://mongodb:27017/eventdb"
  port: "5000"
  jwtSecret: "random"

mongodb:
  name: mongodb
  image:
    repository: mongo
    tag: "8.0"
  service:
    name: mongodb
    port: 27017
  storage:
    size: 1Gi