---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventapp
  template:
    metadata:
      labels:
        app: eventapp
      generateName: eventapp-
    spec:
      containers:
      - name: eventapp
        image: oluty/eventapp:latest
        # imagePullPolicy: Never
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: eventapp-config
      initContainers:
      - name: wait-for-mongodb
        image: busybox
        command: ['sh', '-c', 'until nc -z mongodb 27017; do echo waiting for mongodb; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: eventapp
spec:
  selector:
    app: eventapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort